name: Fix Go Sum
on: [push, workflow_dispatch]
jobs:
  fix:
      runs-on: ubuntu-latest    steps:
            - uses: actions/checkout@v4
                  - uses: actions/setup-go@v5
                          with:
                                    go-version: '1.22'
                                          - run: go mod tidy
                                                - name: Commit changes
                                                        run: |
                                                                  git config --global user.name 'github-actions'
                                                                            git config --global user.email 'github-actions@github.com'
                                                                                      git add .
                                                                                                git commit -m "fix: generate go.sum" || exit 0
                                                                                                          git push
                                                                                                          
