name: fix
on: push
jobs:
  fix:
      runs-on: ubuntu-latest
          steps:
                - uses: actions/checkout@v4
                      - uses: actions/setup-go@v5
                              with:
                                        go-version: '1.22'
                                              - run: go mod tidy
                                                    - run: |
                                                              git config user.name x
                                                                        git config user.email x
                                                                                  git add .
                                                                                            git commit -m x || exit 0
                                                                                                      git push
                                                                                                      
